version: '3.8'

services:
  api:
    build:
      context: ./fake-news-detection-api
      dockerfile: Dockerfile
    image: fake-news-api:dev
    container_name: fake-news-detection-api
    volumes:
      - ./fake-news-detection-api/app:/app/app:ro
      - ./secrets:/app/secrets:ro
    ports:
      - "8000:8000"
    env_file:
      - .env

  ui:
    build:
      context: ./fake-news-detection-ui
      dockerfile: Dockerfile
      target: dev            # use the "dev" stage for hot-reload
    image: fake-news-ui:dev
    container_name: fake-news-detection-ui
    volumes:
      - ./fake-news-detection-ui:/usr/src/app       # mount source for live changes
      - /usr/src/app/node_modules                   # preserve container dependencies
      - ./.env:/usr/src/app/.env:ro                 # pass CRA envs into dev server
    ports:
      - "3000:3000"                               # CRA dev server port
    environment:
      - CHOKIDAR_USEPOLLING=true                     # enable polling for file watching

networks:
  default:
    driver: bridge
